- hosts: ubuntu_servers
  # serial: 1  # Process one host at a time
  become: yes
  tasks:
    - name: Ensure update-manager-core is installed
      apt:
        name: update-manager-core
        state: present

    - name: Ensure release upgrades are enabled
      lineinfile:
        path: /etc/update-manager/release-upgrades
        regexp: '^Prompt='
        line: 'Prompt=lts'

    - name: Get current Ubuntu version
      command: lsb_release -rs
      register: current_version
      changed_when: false

    - name: Debug current Ubuntu version
      debug:
        msg: "Current Ubuntu version: {{ current_version.stdout }}"

    - name: Upgrade to Ubuntu 24.04.2
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      register: upgrade_result
      when: "'24.04' not in current_version.stdout"

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
        msg: "Rebooting after release upgrade"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists
