---
- name: Install and configure Prometheus Node Exporter
  hosts: node-exporter-monitored
  become: true
  tasks:
    - name: Install Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present
        update_cache: yes

    - name: Start and enable Node Exporter service
      service:
        name: node_exporter
        state: started
        enabled: true

- name: Update Prometheus configuration
  hosts: automation1.cal
  become: true
  tasks:
    - name: Create Prometheus scrape config for node exporters
      blockinfile:
        path: /etc/prometheus/prometheus.yml
        block: |
          scrape_configs:
            - job_name: 'node-exporter'
              static_configs:
                - targets: [
                    {% for host in groups['node-exporter-monitored'] %}
                    '{{ hostvars[host].ansible_host }}:9100'{% if not loop.last %},{% endif %}
                    {% endfor %}
                  ]
        insertafter: '^scrape_configs:'
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK - NODE EXPORTERS"

    - name: Reload Prometheus
      systemd:
        name: prometheus
        state: reloaded 